### ISSUE TITLE
Show thumbnail on player

### ISSUE THREAD

**Issue by kjartanvest** [SYNQfm/SYNQ-Android#12]

**Comment by kjartanvest** [comment]
No support in EasyVideoPlayer. Might need to switch to another player to get thumbnail support

**Comment by jettlin** [comment]
Not sure this is needed... It shows the first frame of the video in the background.  Customers can set their own configurations if they need a still frame (and probably won't be using our default player)...

**Comment by jettlin** [comment]
Not going to stress about this.  Thumbnails will be shown on the list of videos after revamp.
